# Generated by CMake 2.8.3

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("fltk_LIB_DEPENDS" "general;wsock32;general;comctl32;")
  SET("fltk_forms_LIB_DEPENDS" "general;fltk;")
  SET("fltk_gl_LIB_DEPENDS" "general;fltk;general;glu32;general;opengl32;")
  SET("fltk_images_LIB_DEPENDS" "general;fltk;general;fltk_png;general;fltk_jpeg;general;fltk_zlib;")
  SET("fltk_png_LIB_DEPENDS" "general;fltk_zlib;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("fltk_LIB_DEPENDS" "wsock32;comctl32;")
  SET("fltk_forms_LIB_DEPENDS" "fltk;")
  SET("fltk_gl_LIB_DEPENDS" "fltk;glu32;opengl32;")
  SET("fltk_images_LIB_DEPENDS" "fltk;fltk_png;fltk_jpeg;fltk_zlib;")
  SET("fltk_png_LIB_DEPENDS" "fltk_zlib;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
